# Generated by Django 4.0.3 on 2022-03-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('product_tagline', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_description', models.TextField()),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(blank=True)),
                ('ingredients', models.CharField(blank=True, max_length=1000, null=True)),
                ('Product_image', models.ImageField(upload_to='photos/products')),
                ('image_gallery_1', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('image_gallery_2', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('image_gallery_3', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('image_gallery_4', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('quantity', models.CharField(blank=True, max_length=20)),
                ('Product_feature1', models.CharField(blank=True, max_length=150)),
                ('Product_feature2', models.CharField(blank=True, max_length=150)),
                ('Product_feature3', models.CharField(blank=True, max_length=150)),
                ('Product_feature4', models.CharField(blank=True, max_length=150)),
                ('Product_feature5', models.CharField(blank=True, max_length=150)),
                ('Product_feature6', models.CharField(blank=True, max_length=150)),
                ('Product_feature7', models.CharField(blank=True, max_length=150)),
                ('amazon_url', models.URLField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
    ]
