# Generated by Django 4.0.3 on 2022-03-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category_tagline', models.CharField(blank=True, max_length=350, null=True)),
                ('category_short_intro', models.CharField(blank=True, max_length=350, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='photos/category')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/category')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/category')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='photos/category')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='photos/category')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
    ]
